### ISSUE TITLE
Cannot connect to upstream service

### ISSUE THREAD

**Issue by avinava-mycelium** [ericlee42/metis-replica-node#17]
I recently pulled in the latest code and followed the instruction as was mentioned.

**dtl** service comes up fine 

```
dtl_1     | {"level":30,"time":1665043947182,"msg":"Service L2_Ingestion_Service is starting..."}
dtl_1     | {"level":30,"time":1665043947183,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
dtl_1     | {"level":30,"time":1665043947184,"msg":"Service L1_Transport_Server can stop now"}
dtl_1     | {"level":30,"time":1665043947768,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043953826,"fromBlock":1001,"toBlock":2001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043958326,"fromBlock":2001,"toBlock":3001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043962779,"fromBlock":3001,"toBlock":4001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043967485,"fromBlock":4001,"toBlock":5001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043971758,"fromBlock":5001,"toBlock":6001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
dtl_1     | {"level":30,"time":1665043975067,"fromBlock":6001,"toBlock":7001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
```

However, the **l2geth** service throws the following error:

`Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: 400 cannot GET http://dtl:7878/eth/context/latest: http error"`

```
l2geth_1  | INFO [10-06|08:13:22.960] Loaded most recent local fast block      number=0 hash=9e3354…716892 td=1 age=53y6mo1w
l2geth_1  | INFO [10-06|08:13:22.961] Regenerated local transaction journal    transactions=0 accounts=0
l2geth_1  | INFO [10-06|08:13:22.961] Running in verifier mode                 sync-backend=l2
l2geth_1  | INFO [10-06|08:13:22.961] Configured rollup client                 url=http://dtl:7878 chain-id=1088 ctc-deploy-height=13626959
l2geth_1  | INFO [10-06|08:13:24.691] Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: 400 cannot GET http://dtl:7878/eth/context/latest: http error"
l2geth_1  | INFO [10-06|08:13:34.420] Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: 400 cannot GET http://dtl:7878/eth/context/latest: http error"
l2geth_1  | INFO [10-06|08:13:43.614] Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: 400 cannot GET http://dtl:7878/eth/context/latest: http error"
```

Any help is hugely appreciated

**Comment by avinava-mycelium** [comment]
Sure, I cloned the repo and just replaced **DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT** with **infura** URL 

Here..

```
version: "3"

services:
  dtl:
    image: metisdao/mvm-andromeda:dtl@sha256:d0b7419f7443510a58d073403fc4add4657ba5b58d41e4c89e41bfbff86c571f
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/addresses.json
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: "<infura-url>"
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: "https://andromeda.metis.io/?owner=1088"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "false"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "true"
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: "1088"
      DATA_TRANSPORT_LAYER__DB_PATH: /data/db
      DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
      DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: "0"
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "100"
      DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "2000"
      DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
      DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
    expose:
      - 7878
    volumes:
      - $PWD/chaindata/dtl:/data
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  l2geth:
    image: metisdao/mvm-andromeda:l2geth-replica@sha256:358d6cc2d72ca1bf7ce046a16f9b39474caff0fbcee37ef93a464cf4bd9dc677
    entrypoint: [ "sh", "/scripts/geth.sh" ]
    restart: unless-stopped
    stop_grace_period: 2m
    env_file:
      - ./geth.env
    environment:
      ROLLUP_BACKEND: l2
      URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/addresses.json
      L2GETH_GENESIS_URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      L2_URL: https://andromeda.metis.io/?owner=1088
      SEQUENCER_CLIENT_HTTP: https://andromeda.metis.io/?owner=1088
      ETH1_CTC_DEPLOYMENT_HEIGHT: 13626959
      EMERGENCY_FORK020222_NUMBER: 750000
    volumes:
      - $PWD/chaindata/l2geth:/root/.ethereum
      - $PWD/scripts:/scripts
    ports:
      - 8546:8546
      - 8545:8545
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
