### ISSUE TITLE
Error: could not detect network

### ISSUE THREAD

**Issue by Percronos** [ericlee42/metis-replica-node#27]
Hey team,

I'm still trying to run a replica node.
I get an error on the dtl container.

```
 $ docker compose up -d
[+] Running 3/3
 ✔ Network metis-replica-node_default     Created                                                                                                                                                    
 ✔ Container metis-replica-node-dtl-1     Healthy                                                                                                                                                    
 ✔ Container metis-replica-node-l2geth-1  Started                                                                                                                                                   
```

```
$ docker compose logs dtl
{"level":50,"time":1703668245717,"extra":{"message":"Error: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.4.5)","stack":"Error: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.4.5)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:199:21)\n    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:208:20)\n    at StaticJsonRpcProvider.<anonymous> (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:491:54)\n    at step (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)","code":"NETWORK_ERROR"},"msg":"Caught an unhandled error"}

```

I've modified DATA_TRANSPORT_LAYER__ADDRESS_MANAGER:
```
-     URL: https://ericlee42.github.io/metis-networks/mainnet/addresses.json
+     DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: "0x918778e825747a892b17C66fe7D24C618262867d"
```
And 
`DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: "https://rpc.ankr.com/eth/07d8f295d05a8b56d2f069c08...."
`

My L1 endpoint is working well.
```
$ curl -X POST https://rpc.ankr.com/eth/07d8f295d05a8b56d2f069c0.... -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x120067b"}
```

Thanks

**Comment by ericlee42** [comment]
I don't think you have a correct docker network configuration.

You can run this `docker run --rm curlimages/curl https://google.com` and see the result.

if you still get an error, you'd better spin up a new instance.

**Comment by Percronos** [comment]
```
$ docker run --rm curlimages/curl https://google.com
Unable to find image 'curlimages/curl:latest' locally
latest: Pulling from curlimages/curl
c926b61bad3b: Pull complete 
fcad2432d35a: Pull complete 
4ca545ee6d5d: Pull complete 
Digest: sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
Status: Downloaded newer image for curlimages/curl:latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   220  100   220    0     0   1750      0 --:--:-- --:--:-- --:--:--  1746
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

I've run it on 2 different GCP compute engine instances (c3d-standard-16)

**Comment by ericlee42** [comment]
```
docker run -it --rm --entrypoint curl metisdao/data-transport-layer:20230713210754 -X POST https://rpc.ankr.com/eth/07d8f295d05a8b56d2f069c0.... -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
```

does it work?

**Comment by ericlee42** [comment]
what the docker-compose file are you using?

I have tested it on a new instance, it works for me.

**Comment by Percronos** [comment]
Yes for docker run on my endpoint

```
$docker run -it --rm --entrypoint curl metisdao/data-transport-layer:20230713210754 -X POST https://rpc.ankr.com/eth/07d8f295d05a8b56d2f069c0876dbe3d21fd...-d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x1200700"}
```

docker-compose.yml:

```
version: "3"

services:
  dtl:
    image: metisdao/data-transport-layer:20230713210754
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: "0x918778e825747a892b17C66fe7D24C618262867d"
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: "https://rpc.ankr.com/eth/07d8f295d05a8b56d2f069c0876d..."
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: "https://andromeda.metis.io/?owner=1088"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "false"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "true"
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: "1088"
      DATA_TRANSPORT_LAYER__DB_PATH: /data/db
      DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
      DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: "0"
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "100"
      DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "2000"
      DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
      DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
    expose:
      - 7878
    volumes:
      - ./chaindata/dtl:/data
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:7878"]
      interval: 5s
      timeout: 3s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  l2geth:
    image: metisdao/l2geth:20230713220744
    entrypoint: ["sh", "/scripts/geth.sh"]
    restart: unless-stopped
    stop_grace_period: 2m
    env_file:
      - ./geth.env
    depends_on:
      dtl:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 6
    environment:
      URL: https://ericlee42.github.io/metis-networks/mainnet/addresses.json
      L2GETH_GENESIS_URL: https://ericlee42.github.io/metis-networks/mainnet/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      L2_URL: https://andromeda.metis.io/?owner=1088
      SEQUENCER_CLIENT_HTTP: https://andromeda.metis.io/?owner=1088
      ETH1_CTC_DEPLOYMENT_HEIGHT: 13626959
      CHAIN_ID: 1088
      NETWORK_ID: 1088
      TARGET_GAS_LIMIT: 1100000000
    volumes:
      - ./chaindata/l2geth:/root/.ethereum
      - ./scripts:/scripts
    ports:
      - 8546:8546
      - 8545:8545
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

```

**Comment by ericlee42** [comment]
It's weird.

if the curl command works, then your compose should work as well.

**Comment by Percronos** [comment]
Yep .. I've tried it on 2 different new VMs and I got the same error.

GCP: c3d-standard-16
Ubuntu: 23.04
Docker install using the apt repo: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

And then, following the documentation.

**Comment by Percronos** [comment]
> It's weird.
> 
> if the curl command works, then your compose should work as well.

Should I try another VM with a different OS ? Or different location ? 
Have you ever tried it on GCP ? 

Thanks

**Comment by ericlee42** [comment]
No, we don't have gcp account.

I can help test it if you can spin up a temporary instance and send me(`eric.l@metis.io`) the ssh credential.

**Comment by ericlee42** [comment]
yep, I'm correct. 

your docker bridge network configuration is not correct.

I don't have much time to help you configure your network

so the simple way to fix it is to use host network.

```yaml
services:
  dtl:
    network_mode: "host"
  l2geth:
    network_mode: "host" 
```

See the /home/ubuntu/metis-replica-node/docker-compose.yml for the deail

![image](https://github.com/ericlee42/metis-replica-node/assets/92196970/8f84dbec-0c5d-41b5-94b8-21b1aab248e2)
